#!/bin/bash
#PBS -P y41
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -l ncpus=48
#PBS -l mem=48GB
#PBS -l software=vasp
#PBS -l storage=scratch/y41
#PBS -m abe
#PBS -M YOUR EMAIL ADDRESS
#PBS -l wd

module load vasp/5.4.4

mpirun vasp_std > output
